DB Instance Snapshot Example
ContainerSolutions/terraform-examples pull request #100
Opened 2021-08-26 22:06 UTC by rodrigorras

Link related issues:
- Resolves # (if merging this resolves the issue)
  -  Add DB snapshot functionality to aws_db_Instance
- Progress towards # (if it's incremental progress)
  - Incremental progress towards #48 

Changes/added features:
- Added Snapshot feature to db_instance examples

The following short checklist should be used to make sure your PR is of good quality and can be merged easily:
- [x] follows [project conventions](https://github.com/ContainerSolutions/terraform-examples#conventions)
- [x] follows [project principles](https://github.com/ContainerSolutions/terraform-examples#principles)
- [x] `./run.sh` works correctly for all new examples
- [x] CI checks pass
- [x] mergeable to main (no conflicts)
- [x] resolved issues linked
- [x] [Milestone](https://github.com/ContainerSolutions/terraform-examples/milestones) linked (if applicable)

Reviewers:
@ianmiell
@ttarczynski
@sanyer
@teszes
@choilmto
@rodrigorras

2021-09-13 10:05 UTC, teszes requested changes
Sorry for being stringy with the comments, but I guess this is a documentation-centric project

2021-10-07 17:24 UTC, rodrigorras commented on aws/aws_db_instance/db_snapshot/main.tf
> +# Summary: Create a DB Instance and take a snapshot(A point in time database backups)
hi @teszes , @ttarczynski just applied the requested changes

2021-11-11 14:43 UTC, DeeAjayi commented
lgtm

2022-03-02 17:12 UTC, melihc1 approved these changes

2022-03-02 17:13 UTC, merged